### ISSUE TITLE
De datum word eerst via een hidden input naar de client gestuurt.

### ISSUE THREAD

**Issue by arnok** [Semware/Kud-Quotes#1]
Nu kan de klint dus de datum manipuleren. Ik stel voor dat de datum direct als parameter in de query word gestopt.

**Comment by timk95** [comment]
Of beter nog NOW(). De mooie functie die MySQL heeft ingebouwd om de datum van nu in te voeren plus tijd (afhankelijk van het veld type)

**Comment by GekkeGeneraal** [comment]
Lijkt me inderdaad een strak plan dan.

**Comment by arnok** [comment]
Ik heb ook het form field weg gehaalt.
Slordig tim.
Iemand sign alsjeblief de pull request.

**Comment by timk95** [comment]
https://github.com/Semware/Kud-Quotes/commit/d8c3907c01417d65500801a087cbd47fecf52c01#diff-828e0013b8f3bc1bb22b4f57172b019d ;)
